name: finwise
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.6.2

  supabase_flutter: ^2.5.6
  # Networking
  dio: ^5.7.0

  # Models & serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.69.0

  # UI utilities
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Logging
  logger: ^2.4.0

  # env
  flutter_dotenv: ^5.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
    # Needed for Hive + widget tests
  path_provider_platform_interface: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.staging
    - .env.prod
